# This file contains global settings for the milk site
---

# SECRET is the site specific key used to encrypt the cookies sent for authentication.
#
# It is very important that this key be both long and unique to each site you build.
#
# My method is to pick two secret passphrases and concatenating the md5 of them together
#
#   >> require 'digest/md5'
#   => true
#   >> Digest::MD5.hexdigest("Milk") + Digest::MD5.hexdigest("Rocks")
#   => "e89b2cbb7d11825a67459af2249064de5cdfbc0ea6e85d2cc3dd5ddec72ffe1a"
SECRET: "098f6bcd4621d373cade4e832627b4f6ad0234829205b9033196ba818f7a872b"

# USE_CACHE is an advanced option for sites that need super high performance.  When
# this option is set to true, then every time a page is saved, a static html file is
# created and saved to [MILK_ROOT]/public/cache/[pagename]/index.html
#
# In order to use these cache files your apache or nginx server needs to have a rewrite
# rule that looks here first and uses the static files if they exist.
#
# As an example, here is the relevent part of my nginx config:
#
#   # Enable loading page cache files directly
#   rewrite ^/$ /cache/Home/index.html;
#   rewrite ^((/[A-Z][A-Za-z]*)+)$ /cache/$1/index.html;
USE_CACHE: false

# You can create any other site wide globals for use in templates here 
SITE_NAME: "Sample Site"
